<a href="https://colab.research.google.com/github/Marcelo-Silvestre/Analise_Dados_Boas_Praticas_PUCRIO/blob/main/Arquivos/mvp_analise_criminal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MvP ANALISE DE DADOS E BOAS PRÁTICAS

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df_crimes_uf = pd.read_excel('https://raw.githubusercontent.com/Marcelo-Silvestre/Analise_Dados_Boas_Praticas_PUCRIO/main/Arquivos/indicadoressegurancapublicauf%20(1).xlsx')
df_crimes_uf

,UF,Tipo Crime,Ano,Mês,Ocorrências
0,Acre,Estupro,2022,janeiro,31
1,Acre,Furto de veículo,2022,janeiro,50
2,Acre,Homicídio doloso,2022,janeiro,10
3,Acre,Lesão corporal seguida de morte,2022,janeiro,1
4,Acre,Roubo a instituição financeira,2022,janeiro,0
...,...,...,...,...,...
23015,Tocantins,Roubo a instituição financeira,2015,dezembro,6
23016,Tocantins,Roubo de carga,2015,dezembro,1
23017,Tocantins,Roubo de veículo,2015,dezembro,55
23018,Tocantins,Roubo seguido de morte (latrocínio),2015,dezembro,2
23019,Tocantins,Tentativa de homicídio,2015,dezembro,42

In [8]:
df_pop_uf = pd.read_excel('https://raw.githubusercontent.com/Marcelo-Silvestre/Analise_Dados_Boas_Praticas_PUCRIO/main/Arquivos/IBGE_populacao__2010_2060.xlsx')
df_pop_uf

,UF,2010,2011,2012,2013,2014,2015,2016,2017,2018,...,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060
0,Acre,765325,778499,792045,805014,818273,831665,844137,856457,869265,...,1168898,1172928,1176619,1179964,1182957,1185600,1187895,1189835,1191419,1192647
1,Alagoas,3195720,3213606,3230877,3247527,3263524,3279222,3293629,3307532,3322379,...,3401028,3386203,3370351,3353463,3335549,3316619,3296685,3275745,3253802,3230875
2,Amapá,694261,711453,728015,744809,762156,779416,796419,813084,829494,...,1249514,1257785,1265743,1273378,1280682,1287654,1294295,1300609,1306591,1312240
3,Amazonas,3553148,3618040,3684326,3751293,3819636,3887740,3952171,4015812,4080611,...,5638304,5664036,5688278,5710995,5732178,5751847,5770028,5786706,5801873,5815537
4,Bahia,14302571,14372994,14441531,14505033,14565807,14629018,14689684,14749868,14812617,...,14688641,14609436,14525993,14438328,14346461,14250434,14150307,14046125,13937968,13825958
5,Ceará,8623766,8681591,8738045,8792607,8847031,8905267,8962834,9018764,9076426,...,9675292,9649120,9620296,9588823,9554693,9517922,9478556,9436622,9392152,9345192
6,Distrito Federal,2639212,2681052,2722198,2763488,2805774,2848633,2890224,2931057,2972209,...,3782994,3788348,3792555,3795598,3797474,3798193,3797772,3796218,3793533,3789728
7,Espírito Santo,3596057,3642595,3689347,3736386,3784361,3832826,3879376,3925341,3972388,...,4895145,4903325,4910373,4916268,4921002,4924594,4927071,4928430,4928667,4927795
8,Goiás,6111792,6214241,6316302,6417591,6520857,6625528,6726130,6824504,6923655,...,8999139,9028359,9055541,9080667,9103727,9124748,9143789,9160881,9176042,9189311
9,Maranhão,6710964,6757213,6798830,6836179,6875302,6916244,6955099,6994148,7035055,...,7578099,7561887,7543659,7523382,7501013,7476542,7449981,7421317,7390534,7357617
10,Mato Grosso,3106513,3145830,3185148,3226030,3269448,3314540,3356979,3398791,3441998,...,4363850,4375775,4386699,4396571,4405356,4413076,4419781,4425472,4430140,4433798
11,Mato Grosso do Sul,2494745,2525762,2557442,2589069,2621214,2653928,2685454,2716534,2748023,...,3400723,3408275,3415039,3421004,3426170,3430552,3434177,3437056,3439191,3440594
12,Minas Gerais,19957444,20096163,20235204,20371328,20508631,20648978,20780264,20908628,21040662,...,22016308,21941633,21861733,21776623,21686312,21590896,21490522,21385216,21275013,21160005
13,Pará,7762953,7862943,7960134,8054419,8149418,8244575,8334346,8422634,8513497,...,10321384,10332358,10340631,10346154,10348902,10348887,10346144,10340650,10332396,10321412
14,Paraíba,3840796,3859813,3875373,3890494,3910059,3932537,3953693,3974437,3996496,...,4202839,4190189,4176432,4161539,4145474,4128245,4109898,4090459,4069934,4048336
15,Paraná,10653276,10738066,10822187,10908262,10997989,11089062,11176203,11261927,11348937,...,12569612,12555362,12538352,12518536,12495904,12470502,12442412,12411670,12378299,12342362
16,Pernambuco,9000873,9062229,9126434,9189504,9252442,9317744,9377368,9434839,9496735,...,10277017,10251890,10223763,10192631,10158518,10121489,10081634,10038990,9993592,9945508
17,Piauí,3192643,3202880,3212635,3220646,3228556,3237691,3246228,3254626,3263754,...,3142736,3124227,3104924,3084843,3063982,3042336,3019911,2996721,2972786,2948119
18,Rio de Janeiro,16303188,16405508,16510627,16616344,16726184,16841138,16947738,17051465,17159960,...,18171147,18127853,18080837,18030039,17975428,17917092,17855161,17789635,17720514,17647842
19,Rio Grande do Norte,3239939,3271415,3302720,3332952,3363084,3393814,3422843,3450669,3479010,...,3904116,3898491,3891770,3883966,3875091,3865173,3854254,3842355,3829494,3815691
20,Rio Grande do Sul,10914795,10963317,11014448,11066527,11119817,11175777,11229947,11280193,11329605,...,11395284,11352547,11307925,11261436,11213094,11162931,11111019,11057418,11002151,10945217
21,Rondônia,1598634,1618210,1637884,1657620,1677766,1698263,1717911,1737578,1757589,...,2120952,2122916,2124363,2125289,2125695,2125590,2124982,2123877,2122283,2120212
22,Roraima,458820,469543,480290,491066,501970,513328,525967,546885,576568,...,933572,940153,946517,952651,958552,964221,969655,974850,979802,984511
23,Santa Catarina,6353055,6441468,6530943,6620186,6710154,6802306,6894058,6984749,7075494,...,8890942,8912269,8931679,8949178,8964776,8978488,8990348,9000381,9008618,9015090
24,São Paulo,42298906,42707383,43119841,43528708,43937755,44356304,44760305,45149603,45538936,...,51377266,51336626,51284187,51220015,51144153,51056719,50958014,50848310,50727840,50596822
25,Sergipe,2108297,2130440,2152329,2173632,2195015,2216657,2237132,2257266,2278308,...,2630096,2629311,2627834,2625660,2622791,2619237,2615013,2610119,2604560,2598353
26,Tocantins,1412989,1431478,1449779,1467474,1485318,1503482,1520448,1537350,1555229,...,1924271,1927565,1930355,1932631,1934389,1935636,1936381,1936619,1936347,1935575